content.pages.consequences = [
    {
        "contentType" : "title",
        "content": "What are the potential unintended consequences of technology?"
    },
    {
        "contentType": "takeaways",
        "content": [
            {
                "contentType": "takeaway",
                "content": "Cities should ask what or who the technology optimizes services for, who could be disproportionately harmed, and who could be excluded.",
            },
            {
                "contentType": "takeaway",
                "content": "Cities must maintain high-quality offline services for those who cannot access digital services while working with nonprofit and corporate partners to close the digital divide. ",
            },
            {
                "contentType": "takeaway",
                "content": "Cities should build a more diverse technology sector, so product and program design better reflect the perspectives of underrepresented communities.",
            },
            {
                "contentType": "caseStudy",
                "content": "Cities are leveraging partnerships to close the digital divide in response to COVID-19 so all residents are included in expanding online civic life."
            }
        ]
    },
    {
        "contentType" : "paragraph",
        "content" : "The city leaders we interviewed emphasized the importance of cities rigorously examining the potential unintended equity consequences of technology programs. They identified the following questions as key to understanding consequences:"
    },
    {
        "contentType" : "unorderedList",
        "content" : [
            "<strong>What (or who) does the technology optimize for?</strong> Technology systems can save cities and residents time and money by effectively optimizing processes. However, it is critical to examine what or who a given technology solution is built to optimize for, and what or who may not have been considered. Pittsburgh director of innovation and performance Santiago Garces illustrated the importance of this question using a smart streetlight solution that a vendor was trying to sell the city. Garces identified that the technology optimized the timing of red lights to minimize the time cars were stopped in traffic. While the technology impressively reduced idling time and CO<sub>2</sub> emissions, it failed to account for pedestrians and bicycles. “The most optimal thing for cars was for a pedestrian to never cross the street, because [the technology] essentially turned the road into a highway,” Garces recalled. “The vendor had to go back to the drawing board to incorporate pedestrians as part of the design.”"
            +"<div class = \"listPBreak\"></div>"
            +"Research has identified several examples of technologies that <a href = \"https://www.vox.com/future-perfect/2019/3/5/18251924/self-driving-car-racial-bias-study-autonomous-vehicle-dark-skin\" target = \"_blank\">systematically perform worse for certain groups</a>, such as <a href = \"https://arxiv.org/pdf/1902.11097.pdf\" target = \"_blank\">autonomous vehicles</a> (PDF) that are more likely to hit dark-skinned pedestrians than light-skinned pedestrians and <a href = \"https://www.nytimes.com/2018/02/09/technology/facial-recognition-race-artificial-intelligence.html?module=inline\" target = \"_blank\">facial recognition software</a> that is more likely to misidentify the gender of dark-skinned people, particularly dark-skinned women. One possible reason is the underrepresentation of the affected groups in the data used to train the system, meaning the resulting algorithm doesn’t effectively “learn” from and optimize for these groups. Another reason could be that the data used to train the model <a href = \"https://medium.com/@harinisuresh/the-problem-with-biased-data-5700005e514c#:~:text=Historical%20bias%20arises%20when%20there,perfect%20sampling%20and%20feature%20selection.\" target = \"_blank\">reflect underlying structural biases and prejudices</a>. Some governments, including <span class = \"frameworkHighliight\"><a href = \"https://www1.nyc.gov/site/adstaskforce/index.page\" target = \"_blank\">New York City</a> and the <a href = \"https://accd.vermont.gov/economic-development/artificial-intelligence-task-force\" target = \"_blank\">State of Vermont</a>, have commissioned task forces</span> to develop recommendations for the responsible use of algorithmic systems by government. Following the release of the New York City task force’s report, the AI Now Institute published a <span class = \"frameworkHighliight\"><a href = \"https://ainowinstitute.org/ads-shadowreport-2019.pdf\" target = \"_blank\">shadow report</a></span> (PDF) that recommended city procurement contracts include provisions requiring vendors to document all data used in developing, implementing, and testing the algorithmic system (training data and input data) and all bias, fairness, and validation-testing performed on the system. The institute also recommended that the city require all departments using an algorithmic system to adopt a standard for assessing disproportionate impact by protected classes.",
            "<strong>Who could be disproportionately harmed?</strong> As discussed above, technology can have disparate impacts across communities and groups—based on both the differential performance of the technology and the potential for the technology to accelerate inequitable systems. When the potential for disproportionate harm is identified, cities should enact policies that require consultation with the impacted communities during design and for disparate impact to be measured and transparently shared with residents, such as the <span class = \"frameworkHighliight\">ACLU’s Community Control Over Police Surveillance (<span class = \"anchorLink different\" data-section=\"risks\" data-anchor=\"ccops\">CCOPS</span>)</span> legislation."
            +"<div class = \"listPBreak\"></div>"
            +"If cities determine that the potential for harm to vulnerable communities from a specific technology cannot be mitigated, then they should not use the technology—or ban it altogether. For example, <span class = \"frameworkHighliight\"><a href = \"https://www.banfacialrecognition.com/map/\" target = \"_blank\">nine US cities</a> in the United States—including <a href = \"https://www.portlandoregon.gov/auditor/article/765749\" target = \"_blank\">Portland</a> (PDF), <a href = \"https://www.vox.com/recode/2019/5/14/18623897/san-francisco-facial-recognition-ban-explained\" target = \"_blank\">San Francisco</a> and <a href = \"https://www.wbur.org/news/2020/06/23/boston-facial-recognition-ban\" target = \"_blank\">Boston</a>—have banned facial recognition technology</span> because of its high likelihood of harm to communities of color. In other cases, the disproportionate harm may come from second-order effects. For example, technology investments such as smart infrastructure can <a href = \"https://www.urban.org/urban-wire/make-smart-cities-more-inclusive-leaders-need-better-tools-and-data\" target = \"_blank\">accelerate displacement pressures</a> in low-income neighborhoods by <a href = \"https://www.reuters.com/article/us-global-cities-tech-inequality/wi-fi-but-no-water-can-smart-tech-help-a-citys-poor-idUSKBN1EU0JF\" target = \"_blank\">increasing rents and property values</a>. Cities should pair companion policies, such as affordable housing policy, with smart city implementation to address these second-order effects.",
            "<strong>Who could be excluded?</strong> Cities also need to examine whether a given technology program could exclude certain residents. When Philadelphia rolled out its Indigo dockless bike system in 2015, it recognized that a card-based payment system would exclude unbanked people and included the <span class = \"frameworkHighliight\">PayNearMe</span> program to enable <a href = \"https://www.rideindego.com/passes/cash-program/\" target = \"_blank\">cash payments</a>—becoming the first city to include a cash payment option for bikeshare at launch. One dimension for exclusion that is particularly relevant to technology programs is the <a href = \"https://time.com/4718032/the-digital-divide/\" target = \"_blank\">digital divide</a>—a lack of access to the internet, internet-enabled devices, and/or digital literacy that is disproportionately concentrated in <a href = \"https://www.ntia.doc.gov/blog/2018/five-digital-inclusion-trends-united-states\" target = \"_blank\">rural and low-income communities</a>. As governments increasingly digitize services, they must maintain <a href = \"https://www.urban.org/research/publication/access-all-innovation-equitable-snap-delivery\" target = \"_blank\">high-quality offline options</a> for those who cannot or prefer not to use online services and undertake efforts to close the digital divide. Adapting government programs to technological change is also critical to ensuring that the individuals who rely on these programs are not excluded from the benefits of new technologies. For example, before the COVID-19 pandemic, the Supplemental Nutrition Assistance Program (SNAP) lacked an online purchasing option in most states. This inequitable access to online purchasing technology increased health risks for SNAP beneficiaries during the COVID-19 pandemic and prompted the Department of Agriculture to rapidly expand its <span class = \"frameworkHighliight\"><a href = \"https://www.urban.org/research/publication/access-all-innovation-equitable-snap-delivery\" target = \"_blank\">SNAP Online Purchasing Pilot</a></span>."
        ]
    },
    {
        "contentType" : "paragraph",
        "content" : "Cities have an imperative not only to question government uses of technology, but to use policy tools to counter the unintended consequences of private technology company actions on residents. Anne Schwieger, broadband and digital equity advocate for the City of Boston, notes that “the reason we have digital equity issue in Boston is because of market failure.” They noted that, for many years, about 90 percent of Boston households had only one internet service provider, and that “making sure there is as much competition as possible” will serve to expand coverage and options for low-income residents. Boston is reforming the permitting process to reduce barriers for new providers and creating the <span class = \"frameworkHighliight\"><a href = \"http://www.bostonplans.org/projects/development-review/article-80-design-review-broadband-ready-buildings\" target = \"_blank\">broadband ready buildings questionnaire</a></span> to ensure that new development maximizes resident broadband choice. Los Angeles is using its permitting power to ensure that low-income neighborhoods are included in private 5G development efforts by requiring companies to have <a href = \"https://www.axios.com/5g-digital-divide-19b70d34-4978-44df-a1cb-ae9222d113ef.html\" target = \"_blank\">equitable coverage</a> in wealthy and “digitally impoverished” neighborhoods. In addition, in response to the COVID-19 pandemic, cities across the United States are working with private companies in new ways to close the digital divide (<span class = \"anchorLink same\" data-anchor=\"covidStudy\">see our case study</span>)."
    },
    {
        "contentType" : "caseStudy",
        "anchor" : "covidStudy",
        "content": [
            {
                "contentType" : "title",
                "content" : "Expanding Broadband Access in Response to COVID-19"
            },
            {
                "contentType" : "paragraph",
                "content" : "As cities issued shelter-in-place orders in spring 2020 to slow the spread of COVID-19, many residents had to quickly adjust to working, educating themselves and their children, and interacting with their governments online. Yet many households in the United States lack the necessary internet connectivity, access to connected devices, and digital literacy to effectively work, educate, and engage online. In 221 large and medium-sized US cities, at least 30 percent of all households still lacked a wireline broadband connection (e.g., cable, fiber optic, or DSL) in 2018.<i class = \"tt-icon\" data-footnote=\"cons1\">?</i> In 92 cities, at least one in five households had no broadband internet of any type, including cellular data plans. This digital divide is highest among low-income households<i class = \"tt-icon\" data-footnote=\"cons2\">?</i> and disproportionately affects people of color<i class = \"tt-icon\" data-footnote=\"cons3\">?</i>—even when accounting for differences in income, education, and employment."
            },
            {
              "contentType" : "paragraph",
                "content" : "In 2020, the Urban Institute surveyed city technology officials to understand how they were closing the digital divide and using technology to meet the needs of their residents in response to COVID-19.<i class = \"tt-icon\" data-footnote=\"cons4\">?</i> The survey revealed that the pandemic made the magnitude of the digital divide clearer or expedited solutions (or both). One technology official from Aurora, Illinois, reflected that “internet isn’t a luxury any more, it’s a necessity.” Cities are undertaking efforts to reduce disparities along all dimensions of the digital divide:"
            },
            {
                "contentType" : "unorderedList",
                "content" : [
                    "Nine of 12 survey respondents indicated that services such as <strong>low-cost or free internet</strong> for residents had expanded since COVID-19.",
                    "Eleven of 12 respondents said that their city was able to provide <strong>expanded access to connected devices</strong> (smartphones, computers, tablets) in response to COVID-19.",
                    "Nine of 10 respondents said that <strong>digital literacy training</strong> had been expanded for their residents since COVID-19."
                ]
            },
            {
              "contentType" : "paragraph",
                "content" : "COVID-19 clearly illuminated how the digital divide excludes affected households from fully participating in digital city services and civic life. Beyond the pandemic, cities must pursue long-term solutions to address the digital divide and ensure all residents can equitably benefit from technology programs."
            }           
        ]
    },
    {
        "contentType" : "paragraph",
        "content" : "Pittsburgh and <span class = \"frameworkHighliight\"><a href = \"https://www.boston.gov/departments/new-urban-mechanics/autonomous-vehicles-bostons-approach\" target = \"_blank\">Boston</a></span> have both established principles governing private development and testing of autonomous vehicle (AV) technologies. Mayor William Peduto’s March 2019 <a href = \"https://apps.pittsburghpa.gov/redtail/images/5056_AV_Testing_EO.pdf\" target = \"_blank\">executive order</a> (PDF) established the <span class = \"frameworkHighliight\">Pittsburgh principles for private companies testing AV technology</span>; these principles included provisions for city oversight, public transparency and data collection, and prioritization of AV technology to achieve “higher occupancy, low or no emissions, lower household transportation costs and greater and more equitable access to opportunity across the City.” Pittsburgh chief equity officer Majestic Lane praised the principles as an example of how cities can “use the power of zoning, variances, and ability [of private companies] to function inside the city to bring different parties together towards an equitable outcome.” However, some <a href = \"https://www.pittsburghforpublictransit.org/wp-content/uploads/2019/07/PPT-AV-paper.pdf\" target = \"_blank\">critics argue</a> (PDF) that the principles don’t go far enough to ensure equity, including the absence of consultation with diverse communities in establishing the principles and a lack of any enforcement mechanism."
    },
    {
        "contentType" : "paragraph",
        "content" : "City governments can also help build a more diverse private and public technology sector. Liana Dragoman, director of Philadelphia’s Service Design Studio, noted that the “design and development community still tends to be largely white, cis-gender, male, and upper or middle class… representation matters, especially when you’re designing products or services that reflect a whole population of people.” To create a design department that reflects the city, Dragoman has found that reaching out to broad audiences—by speaking at public schools, career fairs, and other platforms outside the typical tech-oriented events—is critical to building a diverse network to contact when the department has job openings. Cities are also working to build a more diverse pipeline into the technology workforce. For example, <span class = \"frameworkHighliight\">Pittsburgh’s <a href = \"https://pittsburghpa.gov/onepgh/documents/people/rec2tec.pdf\" target = \"_blank\">Rec2Tech</a> (PDF) program</span> provides free after-school science, technology, engineering, arts, and mathematics (STEAM) programming and meals in the city’s recreation centers to get a diverse group of students interested in STEAM subjects and careers. Efforts like Rec2Tech represent the city’s role in ensuring an inclusive and diverse pipeline for future work."
    }
]